### ISSUE TITLE
"CWLExpressionException: Failed evaluating expression" When scattering

### ISSUE THREAD

**Issue by jeremiahsavage** [rabix/bunny#140]
This might be the same issue as https://github.com/rabix/bunny/issues/97

The following CWL Workflows wrap a CommandLineTool, which completes successfully when scatter is not used, but fails when `dotproduct` scatter is used. 

`git clone https://github.com/jeremiahsavage/cwl_align_pattern.git`

expression works:
```
$ ~/Downloads/rabix-1.0.0-rc2/rabix --verbose ./cwl_align_pattern/works/workflow.cwl ./cwl_align_pattern/works/job.yml 
[2017-02-09 11:47:02.987] [INFO] Pulling docker image alpine:latest
[2017-02-09 11:47:04.457] [INFO] Running command line: echo "file1_1.fq" > file1_realign.bam && echo "file1_2.fq" >> file1_realign.bam && echo "file1.readgroup" >> file1_realign.bam
[2017-02-09 11:47:04.762] [INFO] Job root.align has started
[2017-02-09 11:47:07.559] [INFO] Job root.align has completed
{
  "align_output" : {
    "basename" : "file1_realign.bam",
    "checksum" : "sha1$e6f9fb2f4e90de2cfc53e614a2de1fa60c3becb3",
    "class" : "File",
    "dirname" : "/home/jeremiah/test/cwl_align_pattern/works/bd4446f1-e17f-4eb0-96f2-2a50e858589a/root/align",
    "location" : "/home/jeremiah/test/cwl_align_pattern/works/bd4446f1-e17f-4eb0-96f2-2a50e858589a/root/align/file1_realign.bam",
    "path" : "/home/jeremiah/test/cwl_align_pattern/works/bd4446f1-e17f-4eb0-96f2-2a50e858589a/root/align/file1_realign.bam",
    "secondaryFiles" : [ ],
    "size" : 38
  }
}

```

expression fails:
```
$ ~/Downloads/rabix-1.0.0-rc2/rabix --verbose ./cwl_align_pattern/fails/workflow.cwl ./cwl_align_pattern/fails/jobs.yml 
[2017-02-09 11:48:25.827] [INFO] Pulling docker image alpine:latest
[2017-02-09 11:48:25.827] [INFO] Pulling docker image alpine:latest
[2017-02-09 11:48:28.051] [INFO] Running command line: grep .fq /home/jeremiah/test/cwl_align_pattern/fails/test.bam | xargs touch
[2017-02-09 11:48:28.782] [INFO] Running command line: grep .readgroup /home/jeremiah/test/cwl_align_pattern/fails/test.bam | xargs touch
[2017-02-09 11:48:29.130] [INFO] Job root.bamtofastq has started
[2017-02-09 11:48:29.550] [INFO] Job root.bamtoreadgroup has started
[2017-02-09 11:48:33.163] [INFO] Job root.bamtofastq has completed
[2017-02-09 11:48:34.198] [INFO] Job root.bamtoreadgroup has completed
[2017-02-09 11:48:34.403] [INFO] Pulling docker image alpine:latest
[2017-02-09 11:48:35.264] [ERROR] Failed to build command line.
org.rabix.bindings.cwl.expression.CWLExpressionException: Failed evaluating expression (  '"' + inputs.fastq1_path.path.split('/').slice(-1)[0] + '"' ).
	at org.rabix.bindings.cwl.expression.javascript.CWLExpressionJavascriptResolver.evaluate(CWLExpressionJavascriptResolver.java:89) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.CWLExpressionResolver.javascriptInterpolate(CWLExpressionResolver.java:162) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.CWLExpressionResolver.resolve(CWLExpressionResolver.java:70) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLCommandLineBuilder.buildCommandLineParts(CWLCommandLineBuilder.java:179) [rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLCommandLineBuilder.buildCommandLineObject(CWLCommandLineBuilder.java:62) [rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLBindings.buildCommandLineObject(CWLBindings.java:98) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.start(DockerContainerHandler.java:178) [rabix-backend-local.jar:na]
	at org.rabix.executor.handler.impl.JobHandlerImpl.start(JobHandlerImpl.java:167) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.command.StartCommand.run(StartCommand.java:28) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerCommand.run(JobHandlerCommand.java:50) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerRunnable.run(JobHandlerRunnable.java:59) [rabix-backend-local.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call method "split" of undefined (script#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:3998) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2414) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2407) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1322) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Context.evaluateString(Context.java:1219) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.javascript.CWLExpressionJavascriptResolver.evaluate(CWLExpressionJavascriptResolver.java:69) ~[rabix-backend-local.jar:na]
	... 13 common frames omitted
[2017-02-09 11:48:35.265] [ERROR] Failed to start container.
org.rabix.bindings.BindingException: Failed to build command line.
	at org.rabix.bindings.cwl.CWLCommandLineBuilder.buildCommandLineParts(CWLCommandLineBuilder.java:222) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLCommandLineBuilder.buildCommandLineObject(CWLCommandLineBuilder.java:62) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLBindings.buildCommandLineObject(CWLBindings.java:98) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.start(DockerContainerHandler.java:178) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.handler.impl.JobHandlerImpl.start(JobHandlerImpl.java:167) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.command.StartCommand.run(StartCommand.java:28) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerCommand.run(JobHandlerCommand.java:50) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerRunnable.run(JobHandlerRunnable.java:59) [rabix-backend-local.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: org.rabix.bindings.cwl.expression.CWLExpressionException: Failed evaluating expression (  '"' + inputs.fastq1_path.path.split('/').slice(-1)[0] + '"' ).
	at org.rabix.bindings.cwl.expression.javascript.CWLExpressionJavascriptResolver.evaluate(CWLExpressionJavascriptResolver.java:89) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.CWLExpressionResolver.javascriptInterpolate(CWLExpressionResolver.java:162) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.CWLExpressionResolver.resolve(CWLExpressionResolver.java:70) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLCommandLineBuilder.buildCommandLineParts(CWLCommandLineBuilder.java:179) ~[rabix-backend-local.jar:na]
	... 10 common frames omitted
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call method "split" of undefined (script#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:3998) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2414) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2407) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1322) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Context.evaluateString(Context.java:1219) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.javascript.CWLExpressionJavascriptResolver.evaluate(CWLExpressionJavascriptResolver.java:69) ~[rabix-backend-local.jar:na]
	... 13 common frames omitted
[2017-02-09 11:48:35.266] [ERROR] Failed to start ca5b63be-ff00-4705-b4c6-510b90737049. org.rabix.executor.ExecutorException: Execution failed for ca5b63be-ff00-4705-b4c6-510b90737049. Failed to start container.
org.rabix.executor.ExecutorException: Execution failed for ca5b63be-ff00-4705-b4c6-510b90737049. Failed to start container.
	at org.rabix.executor.handler.impl.JobHandlerImpl.start(JobHandlerImpl.java:170) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.execution.command.StartCommand.run(StartCommand.java:28) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerCommand.run(JobHandlerCommand.java:50) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerRunnable.run(JobHandlerRunnable.java:59) [rabix-backend-local.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: org.rabix.executor.container.ContainerException: Failed to start container.
	at org.rabix.executor.container.impl.DockerContainerHandler.start(DockerContainerHandler.java:235) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.handler.impl.JobHandlerImpl.start(JobHandlerImpl.java:167) ~[rabix-backend-local.jar:na]
	... 6 common frames omitted
Caused by: org.rabix.bindings.BindingException: Failed to build command line.
	at org.rabix.bindings.cwl.CWLCommandLineBuilder.buildCommandLineParts(CWLCommandLineBuilder.java:222) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLCommandLineBuilder.buildCommandLineObject(CWLCommandLineBuilder.java:62) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLBindings.buildCommandLineObject(CWLBindings.java:98) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.start(DockerContainerHandler.java:178) ~[rabix-backend-local.jar:na]
	... 7 common frames omitted
Caused by: org.rabix.bindings.cwl.expression.CWLExpressionException: Failed evaluating expression (  '"' + inputs.fastq1_path.path.split('/').slice(-1)[0] + '"' ).
	at org.rabix.bindings.cwl.expression.javascript.CWLExpressionJavascriptResolver.evaluate(CWLExpressionJavascriptResolver.java:89) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.CWLExpressionResolver.javascriptInterpolate(CWLExpressionResolver.java:162) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.CWLExpressionResolver.resolve(CWLExpressionResolver.java:70) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.CWLCommandLineBuilder.buildCommandLineParts(CWLCommandLineBuilder.java:179) ~[rabix-backend-local.jar:na]
	... 10 common frames omitted
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call method "split" of undefined (script#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:3998) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2414) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2407) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1322) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120) ~[rabix-backend-local.jar:na]
	at org.mozilla.javascript.Context.evaluateString(Context.java:1219) ~[rabix-backend-local.jar:na]
	at org.rabix.bindings.cwl.expression.javascript.CWLExpressionJavascriptResolver.evaluate(CWLExpressionJavascriptResolver.java:69) ~[rabix-backend-local.jar:na]
	... 13 common frames omitted
[2017-02-09 11:48:35.269] [INFO] Failed to start ca5b63be-ff00-4705-b4c6-510b90737049. org.rabix.executor.ExecutorException: Execution failed for ca5b63be-ff00-4705-b4c6-510b90737049. Failed to start container.
[2017-02-09 11:48:35.431] [INFO] Failed to execute a Job
```

**Comment by StarvingMarvin** [comment]
It actually seems to be a separate issue: we already have a fix for #97 on a develop branch, but your example still fails.

**Comment by sinisa88** [comment]
In CWL 1.0 scatter ports are declared without step id. 
Basically 
scatter: [align/fastq1_path, align/fastq2_path, align/readgroup_path]
should be
scatter: [fastq1_path, fastq2_path, readgroup_path]
like in this example: https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/scatter-valuefrom-wf2.cwl
I changed this and run it with build from master and develop and it completed successfully.
As far I can remember this will work with cwltool because it converts this automatically. 
Can you also check are the results ok, and if they are we can close the issue. 
But error logging in this case could definitely be improved.

**Comment by simonovic86** [comment]
@sinisa88 is right. We have to discuss with **cwltool** crew because of theirs internal converters invalid CWL 1.0 workflows are passing and that makes more room for errors and slows down our troubleshooting.

Logging errors needs to be improved definitely.

**Comment by jeremiahsavage** [comment]
It is working for me now with the scatter correctly specified as noted by @sinisa88 

Thank you.
