### ISSUE TITLE
StackOverflowError parsing GDC dnaseq workflow

### ISSUE THREAD

**Issue by jbingham** [rabix/bunny#145]
I'm trying to use Rabix to run the GDC's gdc-dnaseq-cwl workflow. It works for me with cwltool, but with Rabix main branch, I get a StackOverflowError.

Basic info about the setup: I have input files in a subdirectory. The inputs.json file is in the same directory as the other input files. 

What's tricky about the GDC CWL workflow: it has lots of relative paths like ../../tools/something.cwl. I copied the whole directory structure from their github repo to preserve all relative paths. cwltool has no troubles.

Here's the stack trace:

Exception in thread "main" java.lang.StackOverflowError
        at org.rabix.bindings.sb.resolver.SBDocumentResolver.resolve(SBDocumentResolver.java:94)
        at org.rabix.bindings.sb.SBAppProcessor.loadApp(SBAppProcessor.java:20)
        at org.rabix.bindings.sb.SBAppProcessor.loadAppObject(SBAppProcessor.java:25)
        at org.rabix.bindings.sb.SBBindings.loadAppObject(SBBindings.java:59)
        at org.rabix.bindings.BindingsFactory.create(BindingsFactory.java:47)
        at org.rabix.bindings.draft2.bean.Draft2EmbeddedApp.<init>(Draft2EmbeddedApp.java:26)
        at org.rabix.bindings.draft2.json.Draft2JobAppDeserializer.deserialize(Draft2JobAppDeserializer.java:48)
        at org.rabix.bindings.draft2.json.Draft2JobAppDeserializer.deserialize(Draft2JobAppDeserializer.java:20)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
        at org.rabix.common.helper.JSONHelper.readObject(JSONHelper.java:98)
        at org.rabix.common.json.BeanSerializer.deserialize(BeanSerializer.java:26)
        at org.rabix.bindings.draft2.Draft2AppProcessor.loadAppObject(Draft2AppProcessor.java:25)
        at org.rabix.bindings.draft2.Draft2Bindings.loadAppObject(Draft2Bindings.java:59)
        at org.rabix.bindings.BindingsFactory.create(BindingsFactory.java:47)
        at org.rabix.bindings.draft2.bean.Draft2EmbeddedApp.<init>(Draft2EmbeddedApp.java:26)
        at org.rabix.bindings.draft2.json.Draft2JobAppDeserializer.deserialize(Draft2JobAppDeserializer.java:48)
        at org.rabix.bindings.draft2.json.Draft2JobAppDeserializer.deserialize(Draft2JobAppDeserializer.java:20)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)

**Comment by milos-ljubinkovic** [comment]
Hi,

It seems that this issue has been fixed already on the develop branch. I haven't run the worflows, but they can be parsed without that exception unlike the master branch version.

If you don't want to wait for the next release, you can build from the default branch with `mvn clean install -P=all `and find the tar.gz archive in ./rabix-backend-local/target/.

**Comment by jbingham** [comment]
Great. Glad it's fixed. I'm trying to bundle it into an automated script -- I'll wait for it to go into the master branch.

**Comment by StarvingMarvin** [comment]
Actually rc3 git released yesterday, so feel free to try it :)
