### ISSUE TITLE
Failed to run the demo

### ISSUE THREAD

**Issue by jackywu** [rabix/bunny#205]
On my macOS Sierra 10.12.3,  run the command according to the `Running the example` of the homepage, some exception raised.

```
➜  rabix-backend-local-1.0.0-rc3 ./rabix examples/dna2protein/dna2protein.cwl.json examples/dna2protein/inputs.json
[2017-03-11 11:26:23.551] [INFO] Pulling docker image rfranklin/pythondev:latest
[2017-03-11 11:26:32.217] [INFO] Failed to pull docker image. Retrying in 1 seconds
[2017-03-11 11:26:32.225] [ERROR] Method invocation failed. Method public synchronized void org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator.pull(java.lang.String,com.spotify.docker.client.messages.AuthConfig) throws com.spotify.docker.client.DockerException,java.lang.InterruptedException
java.util.concurrent.ExecutionException: java.lang.Exception: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_60]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) ~[na:1.8.0_60]
	at org.rabix.common.retry.RetryMethodInterceptor.callWithTimeout(RetryMethodInterceptor.java:88) ~[rabix-backend-local.jar:na]
	at org.rabix.common.retry.RetryMethodInterceptor.invoke(RetryMethodInterceptor.java:45) ~[rabix-backend-local.jar:na]
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75) [rabix-backend-local.jar:na]
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator$$EnhancerByGuice$$f2f13de3.pull(<generated>) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.pull(DockerContainerHandler.java:130) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.start(DockerContainerHandler.java:167) [rabix-backend-local.jar:na]
	at org.rabix.executor.handler.impl.JobHandlerImpl.start(JobHandlerImpl.java:172) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.command.StartCommand.run(StartCommand.java:28) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerCommand.run(JobHandlerCommand.java:50) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerRunnable.run(JobHandlerRunnable.java:59) [rabix-backend-local.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.Exception: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at org.rabix.common.retry.RetryMethodInterceptor$1.call(RetryMethodInterceptor.java:83) ~[rabix-backend-local.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	... 3 common frames omitted
Caused by: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1306) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1255) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:789) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:773) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator.pull(DockerContainerHandler.java:505) ~[rabix-backend-local.jar:na]
	at org.rabix.common.retry.RetryMethodInterceptor$1.call(RetryMethodInterceptor.java:81) ~[rabix-backend-local.jar:na]
	... 4 common frames omitted
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209) ~[rabix-backend-local.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
	... 4 common frames omitted
[2017-03-11 11:26:36.573] [INFO] Failed to pull docker image. Retrying in 1 seconds
[2017-03-11 11:26:36.575] [ERROR] Method invocation failed. Method public synchronized void org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator.pull(java.lang.String,com.spotify.docker.client.messages.AuthConfig) throws com.spotify.docker.client.DockerException,java.lang.InterruptedException
java.util.concurrent.ExecutionException: java.lang.Exception: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_60]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) ~[na:1.8.0_60]
	at org.rabix.common.retry.RetryMethodInterceptor.callWithTimeout(RetryMethodInterceptor.java:88) ~[rabix-backend-local.jar:na]
	at org.rabix.common.retry.RetryMethodInterceptor.invoke(RetryMethodInterceptor.java:45) ~[rabix-backend-local.jar:na]
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75) [rabix-backend-local.jar:na]
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator$$EnhancerByGuice$$f2f13de3.pull(<generated>) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.pull(DockerContainerHandler.java:130) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.start(DockerContainerHandler.java:167) [rabix-backend-local.jar:na]
	at org.rabix.executor.handler.impl.JobHandlerImpl.start(JobHandlerImpl.java:172) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.command.StartCommand.run(StartCommand.java:28) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerCommand.run(JobHandlerCommand.java:50) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerRunnable.run(JobHandlerRunnable.java:59) [rabix-backend-local.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.Exception: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at org.rabix.common.retry.RetryMethodInterceptor$1.call(RetryMethodInterceptor.java:83) ~[rabix-backend-local.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	... 3 common frames omitted
Caused by: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1306) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1255) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:789) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:773) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator.pull(DockerContainerHandler.java:505) ~[rabix-backend-local.jar:na]
	at org.rabix.common.retry.RetryMethodInterceptor$1.call(RetryMethodInterceptor.java:81) ~[rabix-backend-local.jar:na]
	... 4 common frames omitted
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209) ~[rabix-backend-local.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
	... 4 common frames omitted
[2017-03-11 11:26:38.167] [INFO] Failed to pull docker image. Retrying in 1 seconds
[2017-03-11 11:26:38.168] [ERROR] Method invocation failed. Method public synchronized void org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator.pull(java.lang.String,com.spotify.docker.client.messages.AuthConfig) throws com.spotify.docker.client.DockerException,java.lang.InterruptedException
java.util.concurrent.ExecutionException: java.lang.Exception: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_60]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) ~[na:1.8.0_60]
	at org.rabix.common.retry.RetryMethodInterceptor.callWithTimeout(RetryMethodInterceptor.java:88) ~[rabix-backend-local.jar:na]
	at org.rabix.common.retry.RetryMethodInterceptor.invoke(RetryMethodInterceptor.java:45) ~[rabix-backend-local.jar:na]
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75) [rabix-backend-local.jar:na]
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator$$EnhancerByGuice$$f2f13de3.pull(<generated>) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.pull(DockerContainerHandler.java:130) [rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler.start(DockerContainerHandler.java:167) [rabix-backend-local.jar:na]
	at org.rabix.executor.handler.impl.JobHandlerImpl.start(JobHandlerImpl.java:172) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.command.StartCommand.run(StartCommand.java:28) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerCommand.run(JobHandlerCommand.java:50) [rabix-backend-local.jar:na]
	at org.rabix.executor.execution.JobHandlerRunnable.run(JobHandlerRunnable.java:59) [rabix-backend-local.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.Exception: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at org.rabix.common.retry.RetryMethodInterceptor$1.call(RetryMethodInterceptor.java:83) ~[rabix-backend-local.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	... 3 common frames omitted
Caused by: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rfranklin/pythondev&tag=latest: 500
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1306) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1255) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:789) ~[rabix-backend-local.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:773) ~[rabix-backend-local.jar:na]
	at org.rabix.executor.container.impl.DockerContainerHandler$DockerClientLockDecorator.pull(DockerContainerHandler.java:505) ~[rabix-backend-local.jar:na]
	at org.rabix.common.retry.RetryMethodInterceptor$1.call(RetryMethodInterceptor.java:81) ~[rabix-backend-local.jar:na]
	... 4 common frames omitted
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340) ~[rabix-backend-local.jar:na]
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209) ~[rabix-backend-local.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
	... 4 common frames omitted


```

**Comment by StarvingMarvin** [comment]
Do you have a docker installed and working? Also from the log it seems from the log that rabix tries to contact docker through unix://localhost:80 which doesn't make much sense: it should either be unix://<path to a socket> or http address. What is the vaule of `docker.host` variable in rabix's config/core.properties

**Comment by StarvingMarvin** [comment]
Funny coincidence... After answering you, I got similar message. I resolved the problem by restarting docker daemon.

**Comment by jackywu** [comment]
@StarvingMarvin thanks for answer. after restart docker and dial the vpn ，everything is ok。
