### ISSUE TITLE
NullPointerException on systems without Docker using `--nocontainer`

### ISSUE THREAD

**Issue by chapmanb** [rabix/bunny#337]
I'm running into an issue with 1.0.1 on systems that don't have Docker. When running a workflow using the `--nocontainer` option I get a `NullPointerException`. I've tried doing some editing in `core.properties` without any luck:
```
executor.set_permissions=false
docker.enabled=false
```
Are there other tweaks I can do to avoid needing to have Docker present? Thanks for any suggestions.
```
java.lang.NullPointerException: null
        at org.rabix.engine.service.impl.JobRecordServiceImpl.incrementPortCounter(JobRecordServiceImpl.java:121) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.handler.impl.JobStatusEventHandler.handleLinkPort(JobStatusEventHandler.java:441) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.handler.impl.JobStatusEventHandler.rollOutContainer(JobStatusEventHandler.java:420) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.handler.impl.JobStatusEventHandler.ready(JobStatusEventHandler.java:269) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.handler.impl.JobStatusEventHandler.handle(JobStatusEventHandler.java:123) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.handler.impl.JobStatusEventHandler.handle(JobStatusEventHandler.java:60) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.EventProcessorImpl.send(EventProcessorImpl.java:189) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.MultiEventProcessorImpl.send(MultiEventProcessorImpl.java:54) ~[rabix-cli.jar:na]
        at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50) ~[rabix-cli.jar:na]
        at com.sun.proxy.$Proxy36.send(Unknown Source) ~[na:na]
        at org.rabix.engine.processor.handler.impl.InputEventHandler.handle(InputEventHandler.java:97) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.handler.impl.InputEventHandler.handle(InputEventHandler.java:29) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.EventProcessorImpl.send(EventProcessorImpl.java:189) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.MultiEventProcessorImpl.send(MultiEventProcessorImpl.java:54) ~[rabix-cli.jar:na]
        at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50) ~[rabix-cli.jar:na]
        at com.sun.proxy.$Proxy36.send(Unknown Source) ~[na:na]
        at org.rabix.engine.processor.handler.impl.InitEventHandler.handle(InitEventHandler.java:98) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.handler.impl.InitEventHandler.handle(InitEventHandler.java:34) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.EventProcessorImpl.handle(EventProcessorImpl.java:155) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.EventProcessorImpl.access$300(EventProcessorImpl.java:38) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.EventProcessorImpl$1$1.call(EventProcessorImpl.java:93) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.EventProcessorImpl$1$1.call(EventProcessorImpl.java:90) ~[rabix-cli.jar:na]
        at org.rabix.engine.store.memory.InMemoryRepositoryRegistry.doInTransaction(InMemoryRepositoryRegistry.java:92) ~[rabix-cli.jar:na]
        at org.rabix.engine.processor.impl.EventProcessorImpl$1.run(EventProcessorImpl.java:90) ~[rabix-cli.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[2017-08-25 02:36:52.809] [WARN] Root job 96b46378-bb8f-45fe-97b0-8147d908534e failed.
[2017-08-25 02:36:53.601] [INFO] Failed to execute a Job
```

**Comment by chapmanb** [comment]
I worked through the code and my CWL and determined that the issue isn't due to Docker. The underlying problem was that one of my variable names has a dot (`.`) which causes the issue, likely due to being unable to resolve some component of it. I've swapped bcbio CWL generation over to avoid this, including in the GA4GH workflow challenge so hopefully shouldn't have the problem going forward. I wanted to leave this note in case anyone else gets stuck with the same error. Thanks much.
