### ISSUE TITLE
File location bugs

### ISSUE THREAD

**Issue by milos-ljubinkovic** [rabix/bunny#379]
An issue was found when rabix is called with relative paths to the wf and input files and the input file has a relative path.

**inputs.json:**
```  
{
    "file" : {
      "path" : "human_g1k_v37_decoy.fasta",
      "class":"File"
    }
}
```

/rabix-cli-1.0.3/rabix tool.json job.json

**Comment by kellrott** [comment]
+1 on this bug. 
In a input.json with relative paths, and a workflow that imports tools for the different steps, the input path seems to be a join of the tool directory and the input json. 
So input.json 
```
{
    "file" : {
      "path" : "data/Homo_sapiens_assembly19.fasta",
      "class":"File"
    }
}
```
And workflow with 
```
steps:
    normal_pileup:
      run: ./tools/samtools-pileup-tool/sam_pileup.cwl.yaml
```

Fails with 
```
Caused by: java.nio.file.NoSuchFileException: /mnt/mc3/mc3/./tools/samtools-pileup-tool/data/Homo_sapiens_assembly19.fasta
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_151]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_151]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_151]
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[na:1.8.0_151]
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[na:1.8.0_151]
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[na:1.8.0_151]
        at java.nio.file.Files.readAttributes(Files.java:1737) ~[na:1.8.0_151]
        at java.nio.file.Files.size(Files.java:2332) ~[na:1.8.0_151]
        at org.rabix.bindings.cwl.helper.CWLFileValueHelper.buildMissingInfo(CWLFileValueHelper.java:410) ~[rabix-cli.jar:na]
        at org.rabix.bindings.cwl.processor.callback.CWLFilePropertiesProcessorCallback.process(CWLFilePropertiesProcessorCallback.java:28) ~[rabix-cli.jar:na]
        at org.rabix.bindings.cwl.processor.CWLPortProcessor.processValue(CWLPortProcessor.java:70) ~[rabix-cli.jar:na]
        at org.rabix.bindings.cwl.processor.CWLPortProcessor.processValues(CWLPortProcessor.java:54) ~[rabix-cli.jar:na]
```
